// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAtPfI1_taqwk8F0hkG3OmaXuZUB80n6w',
    appId: '1:796152373618:web:225f6c764f05df5bab3deb',
    messagingSenderId: '796152373618',
    projectId: 'mozae-app-d56ff',
    authDomain: 'mozae-app-d56ff.firebaseapp.com',
    storageBucket: 'mozae-app-d56ff.firebasestorage.app',
    measurementId: 'G-97ZY6JT6TK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlWucpSG_SFdpvLUBzCiaWjFvTwWuFe0g',
    appId: '1:796152373618:android:3a16c48955a89ae5ab3deb',
    messagingSenderId: '796152373618',
    projectId: 'mozae-app-d56ff',
    storageBucket: 'mozae-app-d56ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA99MmfQC9r0uPFoDWnV8c_tU-13lTJYm4',
    appId: '1:796152373618:ios:d5d3660a71ffd220ab3deb',
    messagingSenderId: '796152373618',
    projectId: 'mozae-app-d56ff',
    storageBucket: 'mozae-app-d56ff.firebasestorage.app',
    iosBundleId: 'com.example.mozaeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA99MmfQC9r0uPFoDWnV8c_tU-13lTJYm4',
    appId: '1:796152373618:ios:d5d3660a71ffd220ab3deb',
    messagingSenderId: '796152373618',
    projectId: 'mozae-app-d56ff',
    storageBucket: 'mozae-app-d56ff.firebasestorage.app',
    iosBundleId: 'com.example.mozaeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAtPfI1_taqwk8F0hkG3OmaXuZUB80n6w',
    appId: '1:796152373618:web:7323451000e28118ab3deb',
    messagingSenderId: '796152373618',
    projectId: 'mozae-app-d56ff',
    authDomain: 'mozae-app-d56ff.firebaseapp.com',
    storageBucket: 'mozae-app-d56ff.firebasestorage.app',
    measurementId: 'G-Y95QNJ9DVH',
  );
}
